# Generated by Django 3.2.5 on 2022-01-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_alter_request_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_id',
            field=models.AutoField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
