# Generated by Django 3.2.5 on 2022-01-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_request_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='hosiptal',
        ),
        migrations.RemoveField(
            model_name='request',
            name='pincode',
        ),
        migrations.AddField(
            model_name='request',
            name='attender_pno',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='blood_accepted',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='donation_pincode',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='hosiptal_pincode',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='hospital_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='isDropAvailable',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='isPickupAvailable',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='more_info',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='purpose',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='user_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='verifications',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='request',
            name='attender_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='blood_group',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='quantity',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
