# Generated by Django 3.2.5 on 2022-01-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_auto_20220117_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='discomforts',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='medications',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='test_reports',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
